apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detection-engine
  namespace: default
  labels:
    app: anomaly-detection-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomaly-detection-engine
  template:
    metadata:
      labels:
        app: anomaly-detection-engine
    spec:
      containers:
        - name: anomaly-detection-engine
          image: anomaly-detection-engine:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus:9090"
            - name: HEALING_ENGINE_URL
              value: "http://healing-engine:5000/alert"
            - name: DASHBOARD_URL
              value: "http://autoheal-dashboard-service:8080"
            - name: POLL_INTERVAL
              value: "5"
            - name: CONTAMINATION
              value: "0.05"
          volumeMounts:
            - name: code
              mountPath: /app/main.py
              subPath: main.py
      volumes:
        - name: code
          configMap:
            name: anomaly-engine-code
